import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import { UserProvider } from "@/context/UserContext";
import ThemeRegistry from "@/components/ThemeRegistry";
import { SocketProvider } from "@/context/SocketContext";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <UserProvider>
                    <SocketProvider>
                        <ThemeRegistry>
                            {children}
                        </ThemeRegistry>
                    </SocketProvider>
                </UserProvider>
            </body>
        </html>
    );
}